{% set name = "qubovert" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qubovert-{{ version }}.tar.gz
  sha256: fae18be6be59df70cb04c985f0c9491804e6fa5ef3798e0dbffd2d6357af2e58

build:
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - qubovert
  commands:
    - pip check
  requires:
    - pip
    - python -c "from qubovert import boolean_var"
    - python -c "from qubovert.sim import _canneal"

about:
  home: https://github.com/jtiosue/qubovert
  summary: A package for formulating, simulating, and solving problems in boolean and spin form
  dev_url: https://github.com/jtiosue/qubovert
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - henrikarhula
